export const TEXT_SIZES = {
  "6xl": {
    base: "text-6xl",
    sm: "sm:text-6xl",
    md: "md:text-6xl",
    lg: "lg:text-6xl",
    xl: "xl:text-6xl",
    "2xl": "2xl:text-6xl",
  },
  "5xl": {
    base: "text-5xl",
    sm: "sm:text-5xl",
    md: "md:text-5xl",
    lg: "lg:text-5xl",
    xl: "xl:text-5xl",
    "2xl": "2xl:text-5xl",
  },
  "4xl": {
    base: "text-4xl",
    sm: "sm:text-4xl",
    md: "md:text-4xl",
    lg: "lg:text-4xl",
    xl: "xl:text-4xl",
    "2xl": "2xl:text-4xl",
  },
  "3xl": {
    base: "text-3xl",
    sm: "sm:text-3xl",
    md: "md:text-3xl",
    lg: "lg:text-3xl",
    xl: "xl:text-3xl",
    "2xl": "2xl:text-3xl",
  },
  "2xl": {
    base: "text-2xl",
    sm: "sm:text-2xl",
    md: "md:text-2xl",
    lg: "lg:text-2xl",
    xl: "xl:text-2xl",
    "2xl": "2xl:text-2xl",
  },
  xl: {
    base: "text-xl",
    sm: "sm:text-xl",
    md: "md:text-xl",
    lg: "lg:text-xl",
    xl: "xl:text-xl",
    "2xl": "2xl:text-xl",
  },
  lg: {
    base: "text-lg",
    sm: "sm:text-lg",
    md: "md:text-lg",
    lg: "lg:text-lg",
    xl: "xl:text-lg",
    "2xl": "2xl:text-lg",
  },
  md: {
    base: "text-md",
    sm: "sm:text-md",
    md: "md:text-md",
    lg: "lg:text-md",
    xl: "xl:text-md",
    "2xl": "2xl:text-md",
  },
  sm: {
    base: "text-sm",
    sm: "sm:text-sm",
    md: "md:text-sm",
    lg: "lg:text-sm",
    xl: "xl:text-sm",
    "2xl": "2xl:text-sm",
  },
  xs: {
    base: "text-xs",
    sm: "sm:text-xs",
    md: "md:text-xs",
    lg: "lg:text-xs",
    xl: "xl:text-xs",
    "2xl": "2xl:text-xs",
  },
} as const;
